// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelProviderInfo = { id: string, family: string, name: string, baseUrl: string, keyInstructions: string, configured: boolean, conflict: boolean, recommendedModels: Array<string>, supportsModelDiscovery: boolean, };
