// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelCatalogMode } from "./ModelCatalogMode";

export type ModelListParams = {
/**
 * Select a hosted provider without changing the active thread.
 */
providerId?: string | null, catalogMode?: ModelCatalogMode | null, refresh?: boolean | null,
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null,
/**
 * Optional page size; defaults to a reasonable server-side value.
 */
limit?: number | null,
/**
 * When true, include models that are hidden from the default picker list.
 */
includeHidden?: boolean | null, };
